### ISSUE TITLE
Facebook Login issue

### ISSUE THREAD

**Issue by mamayadi** [SinghDigamber/angularfirebase-authentication#1]
Hi, thank you for this tutorial.

But when I login with facebook the the emailVerified return false any suggestion to correct that

Thanks

**Comment by banhaserhij** [comment]
@mamayadi me also. Did you find some solution?

**Comment by mamayadi** [comment]
@banhaserhij not yet

**Comment by AlexanderDH10** [comment]
### Hello, I have solved this problem:

Just do this: Open `auth.service.ts` and add this function
```javascript
// Sign in with Google
  GoogleAuth() {
    return this.AuthLogin(new firebase.auth.GoogleAuthProvider());
  }
//right here:
 FacebookAuth(){
    return this.AuthLogin(new firebase.auth.FacebookAuthProvider());
  }
```
