### ISSUE TITLE
Module '"../../../../node_modules/firebase"' has no exported member 'auth'. 

### ISSUE THREAD

**Issue by AliciaAMT** [SinghDigamber/angularfirebase-authentication#19]
I am left with this module error, resulting in all other 'auth' errors:
auth.services.ts
Module '"../../../../node_modules/firebase"' has no exported member 'auth'. Did you mean to use 'import auth from "../../../../node_modules/firebase"' instead?

The module is installed correctly, so I do not understand why I get this error. Please help. I copied the code exactly.

**Comment by crowflight** [comment]
Hi did you ever find a solution? I am experiencing this as well.
